### ISSUE TITLE
Can't Install Quantum Control Package

### ISSUE THREAD

**Issue by apassenger** [JuliaQuantumControl/QuantumControl.jl#10]
Hello,
I simply tried the following:
1)Press ]
2) add Quantum Control and I got the following error:
Resolving package versions...
ERROR: Unsatisfiable requirements detected for package QuantumControl [8a270532]:
 QuantumControl [8a270532] log:
 ├─possible versions are: [0.0.1-0.0.4, 0.1.0, 0.2.0] or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions [0.0.1-0.0.4, 0.1.0, 0.2.0]
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left

My julia version is 1.4
I also tried the following method:
1)using Pkg
2)Pkg.add("QuantumControl")

How can I install QuantumControl package?
Thanks,

**Comment by goerz** [comment]
`QuantumControl` is not compatible with Julia 1.4. The minimum version is Julia 1.6.
