### ISSUE TITLE
PulseParametrizations should have normalized spelling

### ISSUE THREAD

**Issue by goerz** [JuliaQuantumControl/QuantumControl.jl#66]
`PulseParametrizations` should be `PulseParameterizations` and any `parametrize` should be normalized to `parameterized`.

**Comment by Fe-r-oz** [comment]
I am fixing some broken links, I will take care of this as well. 

Should `TanhSqParametrization`, `SquareParametrization`, `LogisticParametrization`, etc be` TanhSqParameterization,` `SquareParameterization`, `LogisticParameterization` as well, right?

**Comment by goerz** [comment]
The spelling "parametrization" should not be used anywhere in `QuantumControl`. It should always be "parameterization"
