### ISSUE TITLE
Simple example of optimization with dissipation.

### ISSUE THREAD

**Issue by marlloseff** [JuliaQuantumControl/QuantumControl.jl#9]
@goerz I want to find ε1(t), but I am not understanding how to fit the examples to the following Hamiltonian:

H(t) = H0 + ε1(t)H1,

d/dt ρ(t) = -i[H(t), ρ(t)] + L ρ(t) L† - 0.5 L†L ρ(t) - 0.5 ρ(t) L†L

Where H0, H1, L are time independents. Do you or anyone else have any examples?

**Comment by goerz** [comment]
Isn’t that what https://juliaquantumcontrol.github.io/Krotov.jl/examples/rho_3states/ is doing?

**Comment by marlloseff** [comment]
> Isn’t that what https://juliaquantumcontrol.github.io/Krotov.jl/stable/examples/rho_3states/#Example-2:-Optimization-of-a-Dissipative-Quantum-Gate is doing? (That’s Example 2)

Yes, but I didn't understand it, but now it works. I also found your User Manual text, which was very helpful.

**Comment by marlloseff** [comment]
@goerz You have done a great job. I have learned a lot from your texts, and I still have a lot to learn. Thank you.
